name: Build Image
on:
  workflow_dispatch:
    inputs:
        version:
          description: 'acme.sh upstream image version'     
          required: true
          default: 'latest'


jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Image with Buildah
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: acme.sh
        tags: ${{ github.event.inputs.version }}
        containerfiles: |
          ./Containerfile
        build-args: |
          ACMESH_VER=${{ github.event.inputs.version }}

    - name: Push To docker.io
      id: push-to-docker-io
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io/chiyukisoft
        username: ${{ secrets.DOCKER_IO_USERNAME }}
        password: ${{ secrets.DOCKER_IO_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-docker-io.outputs.registry-paths }}"
